name: foundation_fluttify
description: Foundation for `Fluttify`.
version: 0.13.0+1
homepage: https://github.com/fluttify-project/foundation_fluttify
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: me.yohom.foundation_fluttify
        pluginClass: FoundationFluttifyPlugin
      ios:
        pluginClass: FoundationFluttifyPlugin