name: foundation_fluttify
description: A new Flutter project.
version: 0.0.2
author: yohom <382146139@qq.com>
homepage: https://github.com/fluttify-project/foundation_fluttify

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: me.yohom.foundation_fluttify
    pluginClass: FoundationFluttifyPlugin